image: docker:latest

services:
  - docker:dind  # Docker-in-Docker to run containers in the CI environment

stages:
  - build
  - test

before_script:
  # Copy the file stored in ENV_FILE to .env
  - cp "$ENV_FILE" .env

# Build the Docker images using docker compose
build-job:
  stage: build
  script:
    - echo "Building Docker images using docker compose..."
    - docker compose build  # Build all services defined in docker-compose.yml
  only:
    - branches  # Run on all branches

# Run tests using the built Docker images
test-job:
  stage: test
  script:
    - echo "Running tests using docker compose..."
    - docker compose up -d
    - docker compose exec users_service pytest ./tests -v -s
  dependencies:
    - build-job  # Ensure the test job runs only after the image is built
  timeout: 2h
