image: docker:latest  # Use a Docker image

services:
  - docker:dind  # Enable Docker-in-Docker

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the application..."
    - docker build -t myapp-users_service .

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - docker run --rm myapp-users_service pytest

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker-compose up -d
  environment: production
  only:
    - master