image: docker:latest

services:
  - docker:dind  # Docker-in-Docker to run containers in the CI environment

stages:
  - build
  - test

before_script:
  # Create the .env file from the GitLab CI/CD variable
  - echo "$ENV_FILE" > .env
  - docker info  # Check Docker setup

# Build the Docker images using docker compose
build-job:
  stage: build
  script:
    - echo "Building Docker images using docker compose..."
    - docker compose build  # Build all services defined in docker-compose.yml
  only:
    - branches  # Run on all branches

# Run tests using the built Docker images
test-job:
  stage: test
  script:
    - echo "Running tests using docker compose..."
    - docker compose up -d  # Start the services in detached mode
    - docker compose exec users_service pytest --junitxml=report.xml  # Run pytest inside the users_service container
  artifacts:
    reports:
      junit: report.xml  # Save the test report as an artifact for GitLab
  dependencies:
    - build-job  # Ensure the test job runs only after the image is built