version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  users_service:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A src.celery_tasks.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
      - users_service

  celery_beat:
    build: .
    command: celery -A src.celery_tasks.tasks beat --loglevel=info
    depends_on:
      - redis
      - users_service