services:
  postgres:
    container_name: users_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

  redis:
    container_name: users_redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shared_network

  users_service:
    container_name: users_service
    build:
      context: .
    ports:
      - "8004:8004"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8004
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shared_network

  celery_beat:
    container_name: users_celery_beat
    build:
      context: .
    command: celery -A src.celery_tasks.tasks beat --loglevel=info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - shared_network

volumes:
  postgres_data:
  redis_data:

networks:
  shared_network:
    external: true